{
 "title": "Speedtest",
 "description": "Sample Grafana dashboard for metrics collected by prometheus-speedtest-exporter\r\n\r\nSource: https://github.com/lpicanco/prometheus-speedtest-exporter\r\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Download speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "librespeed_download * 1000 * 1000",
     "legendFormat": "Server: {{server}}"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "librespeed_upload * 1000 * 1000",
     "legendFormat": "Server: {{server}}"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expr": "librespeed_ping", "legendFormat": "Server: {{server}}" }
   ]
  }
 ]
}